config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get 'welcome/hello'
  
  resources :users
  resources :todos
  resources :buses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus.rb
class Bus < ApplicationRecord
end

app/models/fari.rb
class User < ApplicationRecord
  validates :name,presence: true  
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :name,presence: true  
    validates :description,presence: true  
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
    def hello
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only: [:edit, :update, :show, :destroy]
    def new 
        @todos = Todo.new
    end
    def create
        @todos = Todo.new(todos_params)
        if @todos.save
            flash[:notice] = "todo was created successfully"
        redirect_to todos_path(@todos)
        else 
            render 'new'
        end
    end
    def show
         
    end
    def edit
       
    end 
    def update
        if @todos.update(todos_params)
            flash[:notice] = "todo was updated successfully"
            redirect_to todos_path(@todos)
        else 
            render 'edit'
        end
    end
        def destroy
             @todos.destroy
             flash[:notice] = "todo was deleted successfully"
             redirect_to todos_path

        end
    def index
        @todos = Todo.all
    end
    private
    def set_todo
         @todos = Todo.find(params[:id])
    end

    def todos_params
        params.require(:todo).permit(:name, :description)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @users = User.new
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @name = "farhat"
  end
  def hello
    @age = 4
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/buses/bus.html.erb
<h1>Hello</h1>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <ul>
    <li><%= msg %></li>
    </ul>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fyp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |name, msg| %>
    <ul>
    <li><%= msg %></li>
    </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<h1>My Form</h1>
<% if @todos.errors.any? %>
<h1> following error preventing the todo from being saved %>
</h1>
<ul>
<% @todos.errors.full_messages.each do |msg| %>
    <li>
    <%= msg %>
    </li>
    <% end %>
    </ul>
    <% end %>
<%= form_for @todos do |f| %>
<p>
<%= f.label :name %>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :description %>
<%= f.text_field :description  %>
</p>
<p> 
<%= f.submit %>
</p>
<% end %>

app/views/todos/edit.html.erb
<h1> edit file exist</h1>
<%= render 'form' %>

app/views/todos/index.html.erb
<h1>Listing all todos</h1>

<p>
<%= link_to "create a todo", new_todo_path %>
</p>

<table>
<tr>
<th>Name</th>
<th>Description</th>
</tr>
<% @todos.each do |todos| %>
    <tr>
    <td><%= todos.name %></td>
    <td><%= todos.description %></td>
    <td><%= link_to "edit", edit_todo_path(todos)%></td>
    <td><%= link_to "show", todo_path(todos) %></td>
    <td><%= link_to "delete", todo_path(todos), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
    <% end %>

</table>

app/views/todos/new.html.erb
<h1>My Form</h1>
<%= render 'form' %>

app/views/todos/show.html.erb
<h1>Showing a Todo</h1>
<p>
name: <%= @todos.name %>
</p>
<p>
description: <%= @todos.description %>
</p>

<%= link_to "edit a todo", edit_todo_path(@todos) %>
<%= link_to "back to todo list", todos_path %>

app/views/users/new.html.erb
<h1>My Form</h1>
<%= form_for @users do |f| %>
<p>
<%= f.label :name %>
<%= f.text_field :name %>
</p>

    <% end %>

app/views/welcome/hello.html.erb
<h1>hello everyone</h1>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>Find me </p>
<h1>
<%= @name %>
</h1>